const employees = [
  {
    id: 1,
    firstNamer: "Jack",
    lastName: "Dupont",
    birthDate: "1974-04-23",
    startDate: "2021-05-24",
    street: "Maple Avenue",
    city: "Springfield",
    state: "California",
    zipCode: "12345",
    department: "Marketing",
  },
  {
    id: 2,
    firstName: "Julie",
    lastName: "Durand",
    birthDate: "1980-06-17",
    startDate: "2023-03-11",
    street: "Willow Street",
    city: "Riverdale",
    state: "New York",
    zipCode: "54321",
    department: "Human Resources",
  },
  {
    id: 3,
    firstName: "Robert",
    lastName: "Johnson",
    birthDate: "1967-01-03",
    startDate: "2014-05-18",
    street: "Oakwood Drive",
    city: "Lakeside",
    state: "Texas",
    zipCode: "67890",
    department: "Engineering",
  },
  {
    id: 4,
    firstName: "Lucas",
    lastName: "PREA",
    birthDate: "2023-08-11",
    startDate: "2023-08-12",
    street: "10 Lotissement les Allors",
    city: "Bas-en-Basset",
    state: "CA",
    zipCode: "43210",
    department: "Engineering",
  },
  {
    id: 5,
    firstName: "David",
    lastName: "Ravel",
    birthDate: "2023-08-02",
    startDate: "2023-08-05",
    street: "rue des bois",
    city: "allemagne",
    state: "CA",
    zipCode: "4",
    department: "Engineering",
  },
  {
    id: 6,
    firstName: "Jack",
    lastName: "Maison",
    birthDate: "2023-08-28",
    startDate: "2023-08-28",
    street: "renon",
    city: "waal",
    state: "CA",
    zipCode: "54",
    department: "Marketing",
  },
  {
    id: 7,
    firstName: "Jack",
    lastName: "Marcel",
    birthDate: "2023-08-29",
    startDate: "2023-08-29",
    street: "jean debois",
    city: "toulon",
    state: "CA",
    zipCode: "54564",
    department: "Marketing",
  },
  {
    id: 8,
    firstName: "Jack",
    lastName: "peter",
    birthDate: "2023-08-08",
    startDate: "2023-08-08",
    street: "ren",
    city: "jon",
    state: "CA",
    zipCode: "3555",
    department: "Engineering",
  },
  {
  id: 9,
    firstName: "Jacky",
    lastName: "Dupont",
    birthDate: "1974-04-23",
    startDate: "2021-05-24",
    street: "Maple Avenue",
    city: "Springfield",
    state: "California",
    zipCode: "12345",
    department: "Marketing",
  },
  {
    id: 10,
    firstName: "Julia",
    lastName: "Durandro",
    birthDate: "1980-06-17",
    startDate: "2023-03-11",
    street: "Willow Street",
    city: "Riverdale",
    state: "New York",
    zipCode: "54321",
    department: "Human Resources",
  },
  {
    id: 11,
    firstName: "Roberta",
    lastName: "Johnsonng",
    birthDate: "1967-01-03",
    startDate: "2014-05-18",
    street: "Oakwood Drive",
    city: "Lakeside",
    state: "Texas",
    zipCode: "67890",
    department: "Engineering",
  },
  {
    id: 12,
    firstName: "Luc",
    lastName: "PRO",
    birthDate: "2023-08-11",
    startDate: "2023-08-12",
    street: "10 Lotissement les Allors",
    city: "Bas-en-Basset",
    state: "CA",
    zipCode: "43210",
    department: "Engineering",
  },
  {
    id: 13,
    firstName: "Davida",
    lastName: "Ravelly",
    birthDate: "2023-08-02",
    startDate: "2023-08-05",
    street: "rue des bois",
    city: "allemagne",
    state: "CA",
    zipCode: "4",
    department: "Engineering",
  },
  {
    id: 14,
    firstName: "Jacky",
    lastName: "Mongt",
    birthDate: "2023-08-28",
    startDate: "2023-08-28",
    street: "renon",
    city: "waal",
    state: "CA",
    zipCode: "54",
    department: "Marketing",
  },
  {
    id: 15,
    firstName: "Jerck",
    lastName: "Marcello",
    birthDate: "2023-08-29",
    startDate: "2023-08-29",
    street: "jean debois",
    city: "toulon",
    state: "CA",
    zipCode: "54564",
    department: "Marketing",
  },
  {
    id: 16,
    firstName: "Jerne",
    lastName: "peter",
    birthDate: "2023-08-08",
    startDate: "2023-08-08",
    street: "ren",
    city: "jon",
    state: "CA",
    zipCode: "3555",
    department: "Engineering",
  }
];

export default employees;
